import type { Product } from "@/shared/types";

export const mockMiniProducts: Product[] = [
	{
		id: 1,
		name: "Базовая футболка",
		description: "Классическая хлопковая футболка с круглым вырезом.",
		sizes: ["M"],
		article: "TSH-001",
		price: 1499,
		categoryId: 2,
		stock: 25,
		isActive: true,
	},
	{
		id: 2,
		name: "Футболка Oversize",
		description: "Свободный крой, мягкий материал, подходит для повседневного ношения.",
		sizes: ["L"],
		article: "TSH-002",
		price: 1799,
		categoryId: 2,
		stock: 18,
		isActive: true,
	},
	{
		id: 3,
		name: "Худи Classic",
		description: "Удобное худи с капюшоном и карманом кенгуру.",
		sizes: ["L"],
		article: "HD-101",
		price: 2999,
		categoryId: 3,
		stock: 12,
		isActive: true,
	},
	{
		id: 4,
		name: "Худи на молнии",
		description: "Практичное худи на молнии с мягким внутренним слоем.",
		sizes: ["XL"],
		article: "HD-102",
		price: 3299,
		categoryId: 3,
		stock: 8,
		isActive: true,
	},
	{
		id: 5,
		name: "Лонгслив Basic",
		description: "Длинный рукав, приятный к телу материал, подходит для любого сезона.",
		sizes: ["M"],
		article: "LS-201",
		price: 1899,
		categoryId: 4,
		stock: 20,
		isActive: true,
	},
	{
		id: 6,
		name: "Лонгслив с принтом",
		description: "Белый лонгслив с минималистичным принтом на груди.",
		sizes: ["S"],
		article: "LS-202",
		price: 1999,
		categoryId: 4,
		stock: 14,
		isActive: true,
	},
	{
		id: 7,
		name: "Спортивные брюки",
		description: "Удобные брюки с манжетами и шнурком на поясе.",
		sizes: ["L"],
		article: "TR-301",
		price: 2599,
		categoryId: 5,
		stock: 10,
		isActive: true,
	},
	{
		id: 8,
		name: "Карго брюки",
		description: "Современные карго брюки с боковыми карманами.",
		sizes: ["XL"],
		article: "TR-302",
		price: 2799,
		categoryId: 5,
		stock: 9,
		isActive: true,
	},
	{
		id: 9,
		name: "Футболка унисекс",
		description: "Универсальная модель, доступна в нескольких цветах.",
		sizes: ["M"],
		article: "TSH-003",
		price: 1599,
		categoryId: 2,
		stock: 30,
		isActive: true,
	},
	{
		id: 10,
		name: "Худи утеплённое",
		description: "Плотный материал, идеально для прохладной погоды.",
		sizes: ["L"],
		article: "HD-103",
		price: 3499,
		categoryId: 3,
		stock: 7,
		isActive: true,
	},
	{
		id: 11,
		name: "Футболка Slim Fit",
		description: "Приталенная футболка из эластичного хлопка.",
		sizes: ["S"],
		article: "TSH-004",
		price: 1699,
		categoryId: 2,
		stock: 22,
		isActive: true,
	},
	{
		id: 12,
		name: "Футболка с логотипом",
		description: "Модель с фирменным логотипом на груди.",
		sizes: ["M"],
		article: "TSH-005",
		price: 1899,
		categoryId: 2,
		stock: 15,
		isActive: true,
	},
	{
		id: 13,
		name: "Футболка Vintage",
		description: "Эффект состаренной ткани и свободный крой.",
		sizes: ["L"],
		article: "TSH-006",
		price: 1999,
		categoryId: 2,
		stock: 11,
		isActive: true,
	},
	{
		id: 14,
		name: "Худи Oversize",
		description: "Объёмное худи для комфортных образов.",
		sizes: ["XL"],
		article: "HD-104",
		price: 3599,
		categoryId: 3,
		stock: 6,
		isActive: true,
	},
	{
		id: 15,
		name: "Худи с принтом",
		description: "Яркий принт на спине и мягкий начёс внутри.",
		sizes: ["M"],
		article: "HD-105",
		price: 3399,
		categoryId: 3,
		stock: 13,
		isActive: true,
	},
	{
		id: 16,
		name: "Худи Minimal",
		description: "Лаконичный дизайн без лишних деталей.",
		sizes: ["S"],
		article: "HD-106",
		price: 2899,
		categoryId: 3,
		stock: 17,
		isActive: true,
	},
	{
		id: 17,
		name: "Лонгслив Oversize",
		description: "Свободный крой и мягкий хлопковый материал.",
		sizes: ["L"],
		article: "LS-203",
		price: 2099,
		categoryId: 4,
		stock: 16,
		isActive: true,
	},
	{
		id: 18,
		name: "Лонгслив Slim",
		description: "Облегающий крой, подходит для базового гардероба.",
		sizes: ["M"],
		article: "LS-204",
		price: 2199,
		categoryId: 4,
		stock: 19,
		isActive: true,
	},
	{
		id: 19,
		name: "Лонгслив с воротником",
		description: "Модель с высоким воротником для прохладной погоды.",
		sizes: ["XL"],
		article: "LS-205",
		price: 2299,
		categoryId: 4,
		stock: 9,
		isActive: true,
	},
	{
		id: 20,
		name: "Брюки Jogger",
		description: "Современный фасон с эластичным поясом.",
		sizes: ["M"],
		article: "TR-303",
		price: 2699,
		categoryId: 5,
		stock: 14,
		isActive: true,
	},
	{
		id: 21,
		name: "Брюки Classic",
		description: "Прямой крой, универсальный дизайн.",
		sizes: ["L"],
		article: "TR-304",
		price: 2899,
		categoryId: 5,
		stock: 12,
		isActive: true,
	},
	{
		id: 22,
		name: "Брюки утеплённые",
		description: "Плотный материал для холодного времени года.",
		sizes: ["XL"],
		article: "TR-305",
		price: 3199,
		categoryId: 5,
		stock: 7,
		isActive: true,
	},
	{
		id: 23,
		name: "Футболка Sport",
		description: "Лёгкая ткань с влагоотводящими свойствами.",
		sizes: ["S"],
		article: "TSH-007",
		price: 1799,
		categoryId: 2,
		stock: 18,
		isActive: true,
	},
	{
		id: 24,
		name: "Футболка Premium",
		description: "Плотный хлопок и улучшенная посадка.",
		sizes: ["M"],
		article: "TSH-008",
		price: 2199,
		categoryId: 2,
		stock: 10,
		isActive: true,
	},
	{
		id: 25,
		name: "Футболка Basic Black",
		description: "Чёрная базовая модель на каждый день.",
		sizes: ["L"],
		article: "TSH-009",
		price: 1499,
		categoryId: 2,
		stock: 28,
		isActive: true,
	},
	{
		id: 26,
		name: "Худи Street",
		description: "Уличный стиль и свободный силуэт.",
		sizes: ["L"],
		article: "HD-107",
		price: 3699,
		categoryId: 3,
		stock: 5,
		isActive: true,
	},
	{
		id: 27,
		name: "Худи Sport",
		description: "Идеально подходит для активного отдыха.",
		sizes: ["M"],
		article: "HD-108",
		price: 3299,
		categoryId: 3,
		stock: 9,
		isActive: true,
	},
	{
		id: 28,
		name: "Худи Basic Grey",
		description: "Серое худи с минималистичным дизайном.",
		sizes: ["S"],
		article: "HD-109",
		price: 2999,
		categoryId: 3,
		stock: 20,
		isActive: true,
	},
	{
		id: 29,
		name: "Лонгслив Classic White",
		description: "Белый лонгслив из мягкого хлопка.",
		sizes: ["M"],
		article: "LS-206",
		price: 1899,
		categoryId: 4,
		stock: 21,
		isActive: true,
	},
	{
		id: 30,
		name: "Лонгслив Dark",
		description: "Тёмная модель для повседневных образов.",
		sizes: ["L"],
		article: "LS-207",
		price: 1999,
		categoryId: 4,
		stock: 13,
		isActive: true,
	},
	{
		id: 31,
		name: "Брюки Slim",
		description: "Облегающий фасон и современный стиль.",
		sizes: ["S"],
		article: "TR-306",
		price: 2799,
		categoryId: 5,
		stock: 8,
		isActive: true,
	},
	{
		id: 32,
		name: "Брюки Urban",
		description: "Городской стиль и комфортная посадка.",
		sizes: ["M"],
		article: "TR-307",
		price: 2899,
		categoryId: 5,
		stock: 11,
		isActive: true,
	},
	{
		id: 33,
		name: "Брюки Relax",
		description: "Свободный крой для максимального удобства.",
		sizes: ["XL"],
		article: "TR-308",
		price: 2599,
		categoryId: 5,
		stock: 16,
		isActive: true,
	},
	{
		id: 34,
		name: "Футболка Summer",
		description: "Лёгкая модель для тёплой погоды.",
		sizes: ["S"],
		article: "TSH-010",
		price: 1399,
		categoryId: 2,
		stock: 24,
		isActive: true,
	},
	{
		id: 35,
		name: "Футболка Graphic",
		description: "Стильный графический принт спереди.",
		sizes: ["M"],
		article: "TSH-011",
		price: 2099,
		categoryId: 2,
		stock: 12,
		isActive: true,
	},
	{
		id: 36,
		name: "Футболка Soft Touch",
		description: "Особо мягкая ткань премиального качества.",
		sizes: ["L"],
		article: "TSH-012",
		price: 2299,
		categoryId: 2,
		stock: 14,
		isActive: true,
	},
	{
		id: 37,
		name: "Худи Warm",
		description: "Тёплая модель с плотным начёсом.",
		sizes: ["XL"],
		article: "HD-110",
		price: 3799,
		categoryId: 3,
		stock: 4,
		isActive: true,
	},
	{
		id: 38,
		name: "Худи Light",
		description: "Лёгкое худи для межсезонья.",
		sizes: ["M"],
		article: "HD-111",
		price: 3099,
		categoryId: 3,
		stock: 18,
		isActive: true,
	},
	{
		id: 39,
		name: "Лонгслив Sport",
		description: "Подходит для активных тренировок.",
		sizes: ["S"],
		article: "LS-208",
		price: 2199,
		categoryId: 4,
		stock: 10,
		isActive: true,
	},
	{
		id: 40,
		name: "Лонгслив Warm",
		description: "Утеплённая модель для прохладной погоды.",
		sizes: ["L"],
		article: "LS-209",
		price: 2399,
		categoryId: 4,
		stock: 6,
		isActive: true,
	},
	{
		id: 41,
		name: "Брюки Cargo Pro",
		description: "Функциональные карманы и прочная ткань.",
		sizes: ["M"],
		article: "TR-309",
		price: 3099,
		categoryId: 5,
		stock: 9,
		isActive: true,
	},
	{
		id: 42,
		name: "Брюки Street Style",
		description: "Модный фасон для городских образов.",
		sizes: ["L"],
		article: "TR-310",
		price: 2999,
		categoryId: 5,
		stock: 12,
		isActive: true,
	},
	{
		id: 43,
		name: "Футболка Neon",
		description: "Яркий цвет и современный дизайн.",
		sizes: ["XL"],
		article: "TSH-013",
		price: 1999,
		categoryId: 2,
		stock: 17,
		isActive: true,
	},
	{
		id: 44,
		name: "Футболка Classic White",
		description: "Белая универсальная модель.",
		sizes: ["M"],
		article: "TSH-014",
		price: 1499,
		categoryId: 2,
		stock: 26,
		isActive: true,
	},
	{
		id: 45,
		name: "Футболка Classic Grey",
		description: "Серая базовая модель.",
		sizes: ["L"],
		article: "TSH-015",
		price: 1499,
		categoryId: 2,
		stock: 19,
		isActive: true,
	},
	{
		id: 46,
		name: "Худи Graphic",
		description: "Принт на груди и свободная посадка.",
		sizes: ["M"],
		article: "HD-112",
		price: 3499,
		categoryId: 3,
		stock: 8,
		isActive: true,
	},
	{
		id: 47,
		name: "Худи Urban Black",
		description: "Чёрное худи в городском стиле.",
		sizes: ["L"],
		article: "HD-113",
		price: 3599,
		categoryId: 3,
		stock: 10,
		isActive: true,
	},
	{
		id: 48,
		name: "Лонгслив Minimal",
		description: "Минималистичный дизайн без принтов.",
		sizes: ["M"],
		article: "LS-210",
		price: 1899,
		categoryId: 4,
		stock: 15,
		isActive: true,
	},
	{
		id: 49,
		name: "Брюки Sport Line",
		description: "Лёгкие брюки для спорта и отдыха.",
		sizes: ["S"],
		article: "TR-311",
		price: 2699,
		categoryId: 5,
		stock: 13,
		isActive: true,
	},
	{
		id: 50,
		name: "Брюки Premium",
		description: "Премиальная модель с идеальной посадкой.",
		sizes: ["XL"],
		article: "TR-312",
		price: 3399,
		categoryId: 5,
		stock: 6,
		isActive: true,
	},
];
