import type { Product } from "./types";

export const mockProducts: Product[] = [
	{
		id: "1",
		name: "Базовая футболка",
		description: "Классическая хлопковая футболка с круглым вырезом.",
		size: "M",
		article: "TSH-001",
		price: 1499,
		category: "tShirts",
		stock: 25,
	},
	{
		id: "2",
		name: "Футболка Oversize",
		description:
			"Свободный крой, мягкий материал, подходит для повседневного ношения.",
		size: "L",
		article: "TSH-002",
		price: 1799,
		category: "tShirts",
		stock: 18,
	},
	{
		id: "3",
		name: "Худи Classic",
		description: "Удобное худи с капюшоном и карманом кенгуру.",
		size: "L",
		article: "HD-101",
		price: 2999,
		category: "hoodies",
		stock: 12,
	},
	{
		id: "4",
		name: "Худи на молнии",
		description: "Практичное худи на молнии с мягким внутренним слоем.",
		size: "XL",
		article: "HD-102",
		price: 3299,
		category: "hoodies",
		stock: 8,
	},
	{
		id: "5",
		name: "Лонгслив Basic",
		description:
			"Длинный рукав, приятный к телу материал, подходит для любого сезона.",
		size: "M",
		article: "LS-201",
		price: 1899,
		category: "longSleeves",
		stock: 20,
	},
	{
		id: "6",
		name: "Лонгслив с принтом",
		description: "Белый лонгслив с минималистичным принтом на груди.",
		size: "S",
		article: "LS-202",
		price: 1999,
		category: "longSleeves",
		stock: 14,
	},
	{
		id: "7",
		name: "Спортивные брюки",
		description: "Удобные брюки с манжетами и шнурком на поясе.",
		size: "L",
		article: "TR-301",
		price: 2599,
		category: "trousers",
		stock: 10,
	},
	{
		id: "8",
		name: "Карго брюки",
		description: "Современные карго брюки с боковыми карманами.",
		size: "XL",
		article: "TR-302",
		price: 2799,
		category: "trousers",
		stock: 9,
	},
	{
		id: "9",
		name: "Футболка унисекс",
		description: "Универсальная модель, доступна в нескольких цветах.",
		size: "M",
		article: "TSH-003",
		price: 1599,
		category: "tShirts",
		stock: 30,
	},
	{
		id: "10",
		name: "Худи утеплённое",
		description: "Плотный материал, идеально для прохладной погоды.",
		size: "L",
		article: "HD-103",
		price: 3499,
		category: "hoodies",
		stock: 7,
	},
];
