import type { Product } from "@/shared/types";

export const mockMiniProducts: Product[] = [
	{
		id: "1",
		name: "Базовая футболка",
		description: "Классическая хлопковая футболка с круглым вырезом.",
		size: "M",
		article: "TSH-001",
		price: 1499,
		category: { id: 2, name: "Футболки", slug: "tShirts" },
		stock: 25,
	},
	{
		id: "2",
		name: "Футболка Oversize",
		description: "Свободный крой, мягкий материал, подходит для повседневного ношения.",
		size: "L",
		article: "TSH-002",
		price: 1799,
		category: { id: 2, name: "Футболки", slug: "tShirts" },
		stock: 18,
	},
	{
		id: "3",
		name: "Худи Classic",
		description: "Удобное худи с капюшоном и карманом кенгуру.",
		size: "L",
		article: "HD-101",
		price: 2999,
		category: { id: 3, name: "Худи", slug: "hoodies" },
		stock: 12,
	},
	{
		id: "4",
		name: "Худи на молнии",
		description: "Практичное худи на молнии с мягким внутренним слоем.",
		size: "XL",
		article: "HD-102",
		price: 3299,
		category: { id: 3, name: "Худи", slug: "hoodies" },
		stock: 8,
	},
	{
		id: "5",
		name: "Лонгслив Basic",
		description: "Длинный рукав, приятный к телу материал, подходит для любого сезона.",
		size: "M",
		article: "LS-201",
		price: 1899,
		category: { id: 4, name: "Лонгсливы", slug: "longSleeves" },
		stock: 20,
	},
	{
		id: "6",
		name: "Лонгслив с принтом",
		description: "Белый лонгслив с минималистичным принтом на груди.",
		size: "S",
		article: "LS-202",
		price: 1999,
		category: { id: 4, name: "Лонгсливы", slug: "longSleeves" },
		stock: 14,
	},
	{
		id: "7",
		name: "Спортивные брюки",
		description: "Удобные брюки с манжетами и шнурком на поясе.",
		size: "L",
		article: "TR-301",
		price: 2599,
		category: { id: 5, name: "Штаны", slug: "trousers" },
		stock: 10,
	},
	{
		id: "8",
		name: "Карго брюки",
		description: "Современные карго брюки с боковыми карманами.",
		size: "XL",
		article: "TR-302",
		price: 2799,
		category: { id: 5, name: "Штаны", slug: "trousers" },
		stock: 9,
	},
	{
		id: "9",
		name: "Футболка унисекс",
		description: "Универсальная модель, доступна в нескольких цветах.",
		size: "M",
		article: "TSH-003",
		price: 1599,
		category: { id: 2, name: "Футболки", slug: "tShirts" },
		stock: 30,
	},
	{
		id: "10",
		name: "Худи утеплённое",
		description: "Плотный материал, идеально для прохладной погоды.",
		size: "L",
		article: "HD-103",
		price: 3499,
		category: { id: 3, name: "Худи", slug: "hoodies" },
		stock: 7,
	},
	{
		id: "11",
		name: "Футболка Slim Fit",
		description: "Приталенная футболка из эластичного хлопка.",
		size: "S",
		article: "TSH-004",
		price: 1699,
		category: { id: 2, name: "Футболки", slug: "tShirts" },
		stock: 22,
	},
	{
		id: "12",
		name: "Футболка с логотипом",
		description: "Модель с фирменным логотипом на груди.",
		size: "M",
		article: "TSH-005",
		price: 1899,
		category: { id: 2, name: "Футболки", slug: "tShirts" },
		stock: 15,
	},
	{
		id: "13",
		name: "Футболка Vintage",
		description: "Эффект состаренной ткани и свободный крой.",
		size: "L",
		article: "TSH-006",
		price: 1999,
		category: { id: 2, name: "Футболки", slug: "tShirts" },
		stock: 11,
	},
	{
		id: "14",
		name: "Худи Oversize",
		description: "Объёмное худи для комфортных образов.",
		size: "XL",
		article: "HD-104",
		price: 3599,
		category: { id: 3, name: "Худи", slug: "hoodies" },
		stock: 6,
	},
	{
		id: "15",
		name: "Худи с принтом",
		description: "Яркий принт на спине и мягкий начёс внутри.",
		size: "M",
		article: "HD-105",
		price: 3399,
		category: { id: 3, name: "Худи", slug: "hoodies" },
		stock: 13,
	},
	{
		id: "16",
		name: "Худи Minimal",
		description: "Лаконичный дизайн без лишних деталей.",
		size: "S",
		article: "HD-106",
		price: 2899,
		category: { id: 3, name: "Худи", slug: "hoodies" },
		stock: 17,
	},
	{
		id: "17",
		name: "Лонгслив Oversize",
		description: "Свободный крой и мягкий хлопковый материал.",
		size: "L",
		article: "LS-203",
		price: 2099,
		category: { id: 4, name: "Лонгсливы", slug: "longSleeves" },
		stock: 16,
	},
	{
		id: "18",
		name: "Лонгслив Slim",
		description: "Облегающий крой, подходит для базового гардероба.",
		size: "M",
		article: "LS-204",
		price: 2199,
		category: { id: 4, name: "Лонгсливы", slug: "longSleeves" },
		stock: 19,
	},
	{
		id: "19",
		name: "Лонгслив с воротником",
		description: "Модель с высоким воротником для прохладной погоды.",
		size: "XL",
		article: "LS-205",
		price: 2299,
		category: { id: 4, name: "Лонгсливы", slug: "longSleeves" },
		stock: 9,
	},
	{
		id: "20",
		name: "Брюки Jogger",
		description: "Современный фасон с эластичным поясом.",
		size: "M",
		article: "TR-303",
		price: 2699,
		category: { id: 5, name: "Штаны", slug: "trousers" },
		stock: 14,
	},
	{
		id: "21",
		name: "Брюки Classic",
		description: "Прямой крой, универсальный дизайн.",
		size: "L",
		article: "TR-304",
		price: 2899,
		category: { id: 5, name: "Штаны", slug: "trousers" },
		stock: 12,
	},
	{
		id: "22",
		name: "Брюки утеплённые",
		description: "Плотный материал для холодного времени года.",
		size: "XL",
		article: "TR-305",
		price: 3199,
		category: { id: 5, name: "Штаны", slug: "trousers" },
		stock: 7,
	},
	{
		id: "23",
		name: "Футболка Sport",
		description: "Лёгкая ткань с влагоотводящими свойствами.",
		size: "S",
		article: "TSH-007",
		price: 1799,
		category: { id: 2, name: "Футболки", slug: "tShirts" },
		stock: 18,
	},
	{
		id: "24",
		name: "Футболка Premium",
		description: "Плотный хлопок и улучшенная посадка.",
		size: "M",
		article: "TSH-008",
		price: 2199,
		category: { id: 2, name: "Футболки", slug: "tShirts" },
		stock: 10,
	},
	{
		id: "25",
		name: "Футболка Basic Black",
		description: "Чёрная базовая модель на каждый день.",
		size: "L",
		article: "TSH-009",
		price: 1499,
		category: { id: 2, name: "Футболки", slug: "tShirts" },
		stock: 28,
	},
	{
		id: "26",
		name: "Худи Street",
		description: "Уличный стиль и свободный силуэт.",
		size: "L",
		article: "HD-107",
		price: 3699,
		category: { id: 3, name: "Худи", slug: "hoodies" },
		stock: 5,
	},
	{
		id: "27",
		name: "Худи Sport",
		description: "Идеально подходит для активного отдыха.",
		size: "M",
		article: "HD-108",
		price: 3299,
		category: { id: 3, name: "Худи", slug: "hoodies" },
		stock: 9,
	},
	{
		id: "28",
		name: "Худи Basic Grey",
		description: "Серое худи с минималистичным дизайном.",
		size: "S",
		article: "HD-109",
		price: 2999,
		category: { id: 3, name: "Худи", slug: "hoodies" },
		stock: 20,
	},
	{
		id: "29",
		name: "Лонгслив Classic White",
		description: "Белый лонгслив из мягкого хлопка.",
		size: "M",
		article: "LS-206",
		price: 1899,
		category: { id: 4, name: "Лонгсливы", slug: "longSleeves" },
		stock: 21,
	},
	{
		id: "30",
		name: "Лонгслив Dark",
		description: "Тёмная модель для повседневных образов.",
		size: "L",
		article: "LS-207",
		price: 1999,
		category: { id: 4, name: "Лонгсливы", slug: "longSleeves" },
		stock: 13,
	},
	{
		id: "31",
		name: "Брюки Slim",
		description: "Облегающий фасон и современный стиль.",
		size: "S",
		article: "TR-306",
		price: 2799,
		category: { id: 5, name: "Штаны", slug: "trousers" },
		stock: 8,
	},
	{
		id: "32",
		name: "Брюки Urban",
		description: "Городской стиль и комфортная посадка.",
		size: "M",
		article: "TR-307",
		price: 2899,
		category: { id: 5, name: "Штаны", slug: "trousers" },
		stock: 11,
	},
	{
		id: "33",
		name: "Брюки Relax",
		description: "Свободный крой для максимального удобства.",
		size: "XL",
		article: "TR-308",
		price: 2599,
		category: { id: 5, name: "Штаны", slug: "trousers" },
		stock: 16,
	},
	{
		id: "34",
		name: "Футболка Summer",
		description: "Лёгкая модель для тёплой погоды.",
		size: "S",
		article: "TSH-010",
		price: 1399,
		category: { id: 2, name: "Футболки", slug: "tShirts" },
		stock: 24,
	},
	{
		id: "35",
		name: "Футболка Graphic",
		description: "Стильный графический принт спереди.",
		size: "M",
		article: "TSH-011",
		price: 2099,
		category: { id: 2, name: "Футболки", slug: "tShirts" },
		stock: 12,
	},
	{
		id: "36",
		name: "Футболка Soft Touch",
		description: "Особо мягкая ткань премиального качества.",
		size: "L",
		article: "TSH-012",
		price: 2299,
		category: { id: 2, name: "Футболки", slug: "tShirts" },
		stock: 14,
	},
	{
		id: "37",
		name: "Худи Warm",
		description: "Тёплая модель с плотным начёсом.",
		size: "XL",
		article: "HD-110",
		price: 3799,
		category: { id: 3, name: "Худи", slug: "hoodies" },
		stock: 4,
	},
	{
		id: "38",
		name: "Худи Light",
		description: "Лёгкое худи для межсезонья.",
		size: "M",
		article: "HD-111",
		price: 3099,
		category: { id: 3, name: "Худи", slug: "hoodies" },
		stock: 18,
	},
	{
		id: "39",
		name: "Лонгслив Sport",
		description: "Подходит для активных тренировок.",
		size: "S",
		article: "LS-208",
		price: 2199,
		category: { id: 4, name: "Лонгсливы", slug: "longSleeves" },
		stock: 10,
	},
	{
		id: "40",
		name: "Лонгслив Warm",
		description: "Утеплённая модель для прохладной погоды.",
		size: "L",
		article: "LS-209",
		price: 2399,
		category: { id: 4, name: "Лонгсливы", slug: "longSleeves" },
		stock: 6,
	},
	{
		id: "41",
		name: "Брюки Cargo Pro",
		description: "Функциональные карманы и прочная ткань.",
		size: "M",
		article: "TR-309",
		price: 3099,
		category: { id: 5, name: "Штаны", slug: "trousers" },
		stock: 9,
	},
	{
		id: "42",
		name: "Брюки Street Style",
		description: "Модный фасон для городских образов.",
		size: "L",
		article: "TR-310",
		price: 2999,
		category: { id: 5, name: "Штаны", slug: "trousers" },
		stock: 12,
	},
	{
		id: "43",
		name: "Футболка Neon",
		description: "Яркий цвет и современный дизайн.",
		size: "XL",
		article: "TSH-013",
		price: 1999,
		category: { id: 2, name: "Футболки", slug: "tShirts" },
		stock: 17,
	},
	{
		id: "44",
		name: "Футболка Classic White",
		description: "Белая универсальная модель.",
		size: "M",
		article: "TSH-014",
		price: 1499,
		category: { id: 2, name: "Футболки", slug: "tShirts" },
		stock: 26,
	},
	{
		id: "45",
		name: "Футболка Classic Grey",
		description: "Серая базовая модель.",
		size: "L",
		article: "TSH-015",
		price: 1499,
		category: { id: 2, name: "Футболки", slug: "tShirts" },
		stock: 19,
	},
	{
		id: "46",
		name: "Худи Graphic",
		description: "Принт на груди и свободная посадка.",
		size: "M",
		article: "HD-112",
		price: 3499,
		category: { id: 3, name: "Худи", slug: "hoodies" },
		stock: 8,
	},
	{
		id: "47",
		name: "Худи Urban Black",
		description: "Чёрное худи в городском стиле.",
		size: "L",
		article: "HD-113",
		price: 3599,
		category: { id: 3, name: "Худи", slug: "hoodies" },
		stock: 10,
	},
	{
		id: "48",
		name: "Лонгслив Minimal",
		description: "Минималистичный дизайн без принтов.",
		size: "M",
		article: "LS-210",
		price: 1899,
		category: { id: 4, name: "Лонгсливы", slug: "longSleeves" },
		stock: 15,
	},
	{
		id: "49",
		name: "Брюки Sport Line",
		description: "Лёгкие брюки для спорта и отдыха.",
		size: "S",
		article: "TR-311",
		price: 2699,
		category: { id: 5, name: "Штаны", slug: "trousers" },
		stock: 13,
	},
	{
		id: "50",
		name: "Брюки Premium",
		description: "Премиальная модель с идеальной посадкой.",
		size: "XL",
		article: "TR-312",
		price: 3399,
		category: { id: 5, name: "Штаны", slug: "trousers" },
		stock: 6,
	},
];
